POST http://localhost:3001/api/persons
content-type: application/json

{
    "number": "1234"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Arto Hellas"
}